apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-secret
  namespace: storage-messaging
spec:
  refreshInterval: 30s
  secretStoreRef: 
    name: vault-backend
    kind: ClusterSecretStore
  target: 
    name: rabbitmq-secret
  data:
  - secretKey: RABBITMQ_DEFAULT_USER
    remoteRef: 
      key: rabbitmq
      property: RABBITMQ_DEFAULT_USER
  - secretKey: RABBITMQ_DEFAULT_PASS
    remoteRef: 
      key: rabbitmq
      property: RABBITMQ_DEFAULT_PASS