apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalog
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/Ghostbusters-ace/micro-trips-gitops.git
    targetRevision: main
    path: manifests/business/catalog
  destination:
    server: https://kubernetes.default.svc
    namespace: micro-trips
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true