---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kubecost-token
  namespace: kubecost
spec:
  encryptedData:
    token: AgAsCwgJkbJGChH8LiiokmK/Xnvm09rc9lVZ5kiyUdwb4ceMIQNk/e2NsMIQWp7oJI0q4CUgkt9nre2qqI2Knz0ghVRvfipzA0pE/ygxo6zG9xqBvBBHHtF4ZOTS79bvFWCB09dVSF/RJ1eVlftCXqqQyMrBD0KIXu4qLiz6OumE1viOr9EKfh+FvENe/lRta32DL+hoBxBjOrZ4gGzkYDHmZOo7GQYpHzgjhTTWoBrYWLbAbaZY33ndp8oB8aOUlUiUeTgBzN7rU121NmMLM6caYAjStjcpZG0SanZ0wGa4VoD46v82al4U5quPwpBdarqRh97arL4KiPmBDJJ/aK7bxcFZ1SAsBLnRvFzvGdG3uAn60ghG0mcpmwhZc9W+fc6xbj6jCzTHMBVHOsimNi/WjPBN3juTnOsEsr0Oj8T2YynwMPYxblQsSK6s1ShlevXjYOh9J5yuC0/MZaDljj7ZWIKe7CWVLtXV2N9oBvFcJ2k3q21mU5ZO6nTJ4GHiVTFV7o+hozR3Ia0XqhcPopR0hPgbqwSJv+olFm7hSC8Xk+Af8aEEZu/ZaYKu0mte2jC4G3M0fIJzyEHoTi9xOlmbfqtVpFtuN6ki0Lzj7mYNttSbqBl2r34ruLkFBO9inNv2C0lg6F2DkqrwosAPtPVizS/nn/kKPEl2WqfRNPi01eg9UhkCQOHQhUfwekOpSiF/4djrvOo6yCgR0dO6+yvZohEYWyG/K/Gk87XqGtEf/o7uKgepEPUc+Yka
  template:
    metadata:
      name: kubecost-token
      namespace: kubecost
