apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  # 1. Prometheus & Grafana
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 87.10.1
    releaseName: kps
    namespace: monitoring
    valuesFile: values-prometheus.yaml

  # 2. Base de données de Logs
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 6.42.0 
    releaseName: loki
    namespace: monitoring
    valuesFile: values-loki.yaml

  # 3. Aspirateur de Logs
  - name: promtail
    repo: https://grafana.github.io/helm-charts
    version: 6.16.0 
    releaseName: promtail
    namespace: monitoring
    valuesFile: values-promtail.yaml