grafana:
  service:
    type: NodePort
    nodePort: 30090
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki.monitoring.svc.cluster.local:3100
      access: proxy
      isDefault: false

prometheus:
  prometheusSpec:
    retention: 2d
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 1Gi

# 2. On dit à Alertmanager d'envoyer les alertes à Mailhog
alertmanager:
  config:
    global:
      smtp_smarthost: 'mailhog.storage-messaging.svc.cluster.local:1025'
      smtp_require_tls: false
      smtp_from: 'alerts@micro-trips.local'
    route:
      receiver: 'mailhog'
    receivers:
      - name: 'mailhog'
        email_configs:
          - to: 'team@micro-trips.local'
            send_resolved: true