apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
  namespace: micro-trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
      - name: booking
        image: ghcr.io/ghostbusters-ace/booking:1788c069944d575ad932bbcb9f7ce4c4b8517fca
        ports:
        - containerPort: 8081