apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: booking-db-secret
  namespace: micro-trips
spec:
  refreshInterval: 30s
  secretStoreRef: 
    name: vault-backend
    kind: ClusterSecretStore
  target: 
    name: booking-db-secret
  data:
  # Mêmes clés dans Vault que pour l'installation de Postgres
  - secretKey: POSTGRES_USER
    remoteRef: 
      key: postgres
      property: POSTGRES_USER
  - secretKey: POSTGRES_PASSWORD
    remoteRef: 
      key: postgres
      property: POSTGRES_PASSWORD