apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: micro-trips

resources:
  - external-secret.yaml
  - rollout.yaml
  - service.yaml
  - analysis-template.yaml
  - traffic-generator.yaml