apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: booking
  namespace: micro-trips
spec:
  replicas: 4
  selector:
    matchLabels:
      app: booking
  strategy:
    canary:
      stableService: booking-stable
      canaryService: booking-canary
      steps:
        - setWeight: 20
        - pause: { duration: 2m }
        - analysis:
            templates:
              - templateName: booking-success-rate
            args:
              - name: version-name
                value: "canary"
        - setWeight: 40
        - pause: { duration: 2m }
        - analysis:
            templates:
              - templateName: booking-success-rate
            args:
              - name: version-name
                value: "canary"
        - setWeight: 80
        - pause: { duration: 1m }
        - setWeight: 100
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
        - name: booking
          image: ghcr.io/ghostbusters-ace/booking:v1.0.9
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          env:
            - name: APP_VERSION
              value: "canary"

            # --- INFO DE CONNEXION ---
            - name: DB_HOST
              value: "postgres.storage-messaging.svc.cluster.local" 
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "microtrips"
            
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: booking-db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booking-db-secret
                  key: POSTGRES_PASSWORD