apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave:
spec:
  project: default
  source:
    repoURL: https://github.com/Ghostbusters-ace/micro-trips-gitops.git
    targetRevision: main
    path: manifests/infrastructure/postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: storage-messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true