apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: micro-trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: ghcr.io/ghostbusters-ace/catalog:latest
        ports:
        - containerPort: 8080